version: '3.8'

services:
  babeldoc-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=
      - OPENAI_DEFAULT_MODEL=gpt-4o
      - DEEPSEEK_BASE_URL=https://api.deepseek.com/v1
      - DEEPSEEK_API_KEY=
      - DEEPSEEK_DEFAULT_MODEL=deepseek-chat
      - OLLAMA_BASE_URL=http://localhost:11434/v1
      - OLLAMA_API_KEY=
      - OLLAMA_DEFAULT_MODEL=llama3
      - SERVER_PORT=7860
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output